FROM anapsix/alpine-java:8_server-jre_unlimited
ENV THIS_PROJECT_NAME=cloud-guli-auth
ADD target/cloud-guli-auth-0.0.1-SNAPSHOT.jar /opt/jar
EXPOSE 10000
CMD java -jar -Dfile.encoding=utf-8 -Xms256m -Xmx500m \
-Dspring.application.name=cloud-guli-auth -Dspring.cloud.nacos.server-addr=nacos:8848 -Dspring.cloud.nacos.discovery=cloud-guli-auth \
-Dspring.redis.host=redis -Dspring.rabbitmq.host=rabbitmq \
/opt/jar/cloud-guli-auth-0.0.1-SNAPSHOT.jar
