#server:
#  port: 2000
#spring:
#  application:
#    name: cloud-guli-member
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:9948
#      config:
#        server-addr: localhost:9948
#        file-extension: yaml
#        group: gulimall
#        namespace: 10086
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://machine111:13306/gulimall_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto