spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://cloud-guli-product
          predicates:
            - Path=/admin/product/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://cloud-guli-fast
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /renren-fast/$\{segment}

        #主页
        - id: gulimall_host
          uri: lb://cloud-guli-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: web_product
          uri: lb://cloud-guli-product
          predicates:
            - Path=/web/product/**
          filters:
            - RewritePath=/web/product/(?<segment>.*), /$\{segment}
