#server:
#  port: 6000
#spring:
#  application:
#    name: cloud-guli-gateway
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        ip: 127.0.0.1
#      config:
#        namespace: 10086006
#        file-extension: yaml
#        extension-configs:
#          - data-id: gateway.yaml
#            group: dev
#            refresh: true
#
#          - data-id: sentinel.yaml
#            group: dev
#            refresh: true
