spring:
  cloud:
    gateway:
      routes:
        #主页
        - id: pika_host
          uri: lb://cloud-guli-product
          predicates:
            - Header=MyHost, (item.)*pikapikachu.tk

        #搜索页
        - id: search_pika_host
          uri: lb://cloud-guli-search
          predicates:
            - Header=MyHost,search.pikapikachu.tk

        #登录,注册页
        - id: auth_pika_host
          uri: lb://cloud-guli-auth
          predicates:
            - Header=MyHost,auth.pikapikachu.tk

        #购物车
        - id: cart_pika_host
          uri: lb://cloud-guli-cart
          predicates:
            - Header=MyHost,cart.pikapikachu.tk

        #订单
        - id: order_pika_host
          uri: lb://cloud-guli-order
          predicates:
            - Header=MyHost,order.pikapikachu.tk

        #会员订单
        - id: member_pika_host
          uri: lb://cloud-guli-member
          predicates:
            - Header=MyHost,member.pikapikachu.tk

        #秒杀
        - id: seckill_pika_host
          uri: lb://cloud-guli-seckill
          predicates:
            - Header=MyHost,seckill.pikapikachu.tk

        #第三方服务
        - id: third_pika_host
          uri: lb://cloud-guli-third-service
          predicates:
            - Header=MyHost,third.pikapikachu.tk
