server:
  port: 7788
spring:
  #  邮箱配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.office365.com
    # 发送者邮箱
    username: GenshinTimeStamp@outlook.com
    # 配置密码，注意这不是真正的密码，而是刚刚申请到的16位授权码
    password: 1187443340@hotmail.com
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #这里完全可以直接用smtp
    protocol: smtp
    test-connection: false
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: false
          auth: true
          socketFactory:
            #这个可要可不要
            class: com.sun.mail.util.MailSSLSocketFactory
            port: 587
          starttls:
            enable: true
            required: true
